version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 10
    reviewers:
      - "ollin"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:15"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 4
    reviewers:
      - "ollin"

